### ISSUE TITLE
update module GFAFFIX

### ISSUE THREAD

**Issue by subwaystation** [nf-core/pangenome#159]
### Description of feature

Depends on https://github.com/marschall-lab/GFAffix/issues/12.

**Comment by subwaystation** [comment]
ah sorry, I already did that: https://github.com/nf-core/pangenome/blob/dev/modules/nf-core/gfaffix/environment.yml

**Comment by heuermh** [comment]
ok, if helpful 0.1.5b has been merged in nf-core/modules
