### ISSUE TITLE
Clean up stale git branches

### ISSUE THREAD

**Issue by heuermh** [nf-core/pangenome#173]
### Description of the bug

Did a `git fetch upstream` recently and noticed we have a lot of stale branches
https://github.com/nf-core/pangenome/branches/stale

Anyone mind if I delete these?

**Comment by heuermh** [comment]
Also, would it be possible to add a label for `chore`?  This isn't really a bug or enhancement.

**Comment by subwaystation** [comment]
Feel free to delete all of these stale branches. Thanks!

**Comment by heuermh** [comment]
Done, thank you!

**Comment by subwaystation** [comment]
They still appear as stale here @heuermh ? Or am I missing something?

**Comment by heuermh** [comment]
Sorry, missed a few pages of results 😬 

Is this one still relevant?
[subwaystation-patch-1](https://github.com/nf-core/pangenome/tree/subwaystation-patch-1)

**Comment by subwaystation** [comment]
no worries, now you got it!
I deleted the branch in question

cheers!
