### ISSUE TITLE
Alternative pangenome construction tool minigraph

### ISSUE THREAD

**Issue by subwaystation** [nf-core/pangenome#20]
# nf-core/pangenome feature request

Hi there!

## Describe the solution you'd like

Instead of generating the graphical pangenome with `edyeet` and `seqwish`, one could use https://github.com/lh3/minigraph and directly plug that into `smoothxg`. However, we would need a conversion from `minigraph`'s rGFA to GFAv1.

**Comment by heuermh** [comment]
> However, we would need a conversion from minigraph's rGFA to GFAv1.

Syntactically those are the same, though `rGFA` has additional required attributes.  What conversion is necessary?

**Comment by subwaystation** [comment]
From my point of view, the major problem is that the data models presented by `minigraph`'s rGFA or `vg`'s GFAv1 are kind of incompatible. The key difference is that rGFA is reference oriented and was not designed to represent a reference-free pangenome graph. GFAv1 allows incorporating sequences as paths in the graph without specifying a reference sequence. These are the `P` lines in GFAv1. Which is not an ideal solution, but a solution.
For further discussions please take a look at https://github.com/lh3/minigraph/issues/26 and https://github.com/lh3/minigraph/issues/27. 
@ekg nicely summarizes the current state in https://github.com/vgteam/vg/issues/3129. Seems like the `vgteam` will work on a solution.

**Comment by subwaystation** [comment]
One proposed harmonizing solution by @ekg is the [Pangenome Graph Variation Format (PGVF)](https://github.com/pangenome/pgvf-spec), but it's not implemented anywhere, yet.

**Comment by subwaystation** [comment]
Updates on the `vg` side: https://github.com/vgteam/vg/pull/3160

**Comment by subwaystation** [comment]
As it turns out, `minigraph` is very simple and can only build graphs with variation down to a size of ~50bp. No base-level alignments are possible. I think this is not a good way to build a pangenome graph. We miss essential parts.
I will only add this here if the users would require it.
