### ISSUE TITLE
way to modify number of threads for edyeet for pangenome pipeline

### ISSUE THREAD

**Issue by dbrami** [nf-core/pangenome#40]
Hi all,
I'm trying to find a way to edit some config file so it will use as many CPUs as available instead of "1" for the edyeet step of pangenome pipeline.
Please let me know.

Best,
Daniel

**Comment by ewels** [comment]
Hi @dbrami,

Please see the documentation about Nextflow configuration: https://nf-co.re/usage/configuration#tuning-workflow-resources

Note that you're generally better off asking for help like this on Slack. You can join [here](https://nf-co.re/join) and find the `#pangenome` channel here: https://nfcore.slack.com/channels/pangenome

Phil
