### ISSUE TITLE
Add MultiQC

### ISSUE THREAD

**Issue by Zethson** [nf-core/pangenome#8]
Hi,

just to keep track of what needs to be done.
We want to integrate MultiQC.

Need to wait for

+ merges of https://github.com/ewels/MultiQC_TestData/pull/178 and https://github.com/ewels/MultiQC/pull/1340
+ a new MultiQC release

**Comment by heuermh** [comment]
Is the version of MultiQC in the fork https://github.com/Imipenem/MultiQC in the upstream Dockerfile via https://github.com/nf-core/pangenome/pull/35 sufficient?

**Comment by Zethson** [comment]
Yes. It implements everything that we need.
But we'll keep this issue open as long as @ewels did not get to review/merge it yet.

**Comment by ewels** [comment]
I'll get there one day! I merged a PR this morning, slow and steady 😅

**Comment by Zethson** [comment]
@ewels no worries. Open-source development is time consuming and stressful. I don't mind it taking longer.

**Comment by subwaystation** [comment]
fixed via #71
